fields:
  - name: "artist"
    type: "STRING"
  - name: "artist_link"
    type: "STRING"
  - name: "genres"
    type: "STRING"
  - name: "popularity"
    type: "INTEGER"
  - name: "ranking_date"
    type: "DATE"
    